name: deploy-auth

on:
  push:
    branches:
      - main
    paths:
      - 'server/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      - run: cd server && docker build -t holdmypotion/icp-server .
      - run: docker push holdmypotion/icp-server
